default:
  app:
    name: Streetlights API
    version: 1.0.0

  broker:
    mqtt:
      url: mqtt://test.mosquitto.org
      topics: ["dalong/measured"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true

development:

test:

staging:

production:
